CREATE TABLE IF NOT EXISTS findesk_workspace_preferences (
    user_id BIGINT UNSIGNED NOT NULL,
    mode ENUM('solo','group') NOT NULL DEFAULT 'solo',
    group_id BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id),
    KEY idx_findesk_workspace_group (group_id),
    CONSTRAINT fk_findesk_workspace_user FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_workspace_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS findesk_transfers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_id BIGINT UNSIGNED NOT NULL,
    issued_by_user_id BIGINT UNSIGNED NOT NULL,
    assigned_to_user_id BIGINT UNSIGNED NOT NULL,
    stream_type ENUM('cash','card') NOT NULL DEFAULT 'cash',
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'EUR',
    description VARCHAR(500) DEFAULT NULL,
    state ENUM('pending','active','cancelled') NOT NULL DEFAULT 'pending',
    on_the_go_tape_id BIGINT UNSIGNED DEFAULT NULL,
    confirmed_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    confirmed_at DATETIME DEFAULT NULL,
    cancelled_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    cancelled_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_findesk_transfers_group_state (group_id, state),
    KEY idx_findesk_transfers_assigned_state (assigned_to_user_id, state),
    KEY idx_findesk_transfers_stream (stream_type),
    KEY idx_findesk_transfers_tape (on_the_go_tape_id),
    CONSTRAINT fk_findesk_transfers_group FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_transfers_issued FOREIGN KEY (issued_by_user_id) REFERENCES users (id) ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_transfers_assigned FOREIGN KEY (assigned_to_user_id) REFERENCES users (id) ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_transfers_confirmed FOREIGN KEY (confirmed_by_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_transfers_cancelled FOREIGN KEY (cancelled_by_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_transfers_tape FOREIGN KEY (on_the_go_tape_id) REFERENCES on_the_go_tapes (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS findesk_transfer_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transfer_id BIGINT UNSIGNED NOT NULL,
    group_id BIGINT UNSIGNED NOT NULL,
    actor_user_id BIGINT UNSIGNED DEFAULT NULL,
    event_type VARCHAR(80) NOT NULL,
    previous_state_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(previous_state_json)),
    new_state_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(new_state_json)),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_findesk_transfer_events_transfer (transfer_id),
    KEY idx_findesk_transfer_events_group (group_id),
    CONSTRAINT fk_findesk_transfer_events_transfer FOREIGN KEY (transfer_id) REFERENCES findesk_transfers (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_transfer_events_group FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_transfer_events_actor FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS findesk_reports (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_id BIGINT UNSIGNED NOT NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    status ENUM('draft','finalized','archived') NOT NULL DEFAULT 'draft',
    period_from DATE DEFAULT NULL,
    period_to DATE DEFAULT NULL,
    cash_summary_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(cash_summary_json)),
    card_summary_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(card_summary_json)),
    total_summary_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(total_summary_json)),
    snapshot_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(snapshot_json)),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    finalized_at DATETIME DEFAULT NULL,
    archived_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_findesk_reports_group_status (group_id, status),
    CONSTRAINT fk_findesk_reports_group FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_reports_creator FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS findesk_report_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_id BIGINT UNSIGNED NOT NULL,
    tape_id BIGINT UNSIGNED NOT NULL,
    owner_user_id BIGINT UNSIGNED NOT NULL,
    stream_type ENUM('cash','card') NOT NULL DEFAULT 'cash',
    state ENUM('ready','attached','detached') NOT NULL DEFAULT 'attached',
    snapshot_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(snapshot_json)),
    attached_at DATETIME DEFAULT NULL,
    detached_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_findesk_report_tape (report_id, tape_id),
    KEY idx_findesk_report_items_tape (tape_id),
    KEY idx_findesk_report_items_owner (owner_user_id),
    CONSTRAINT fk_findesk_report_items_report FOREIGN KEY (report_id) REFERENCES findesk_reports (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_report_items_tape FOREIGN KEY (tape_id) REFERENCES on_the_go_tapes (id) ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_report_items_owner FOREIGN KEY (owner_user_id) REFERENCES users (id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS findesk_protected_actions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_id BIGINT UNSIGNED DEFAULT NULL,
    action_type VARCHAR(120) NOT NULL,
    entity_type VARCHAR(120) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    preview_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(preview_json)),
    previous_state_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(previous_state_json)),
    new_state_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(new_state_json)),
    reason TEXT DEFAULT NULL,
    confirmation_phrase VARCHAR(80) DEFAULT NULL,
    status ENUM('prepared','confirmed','cancelled') NOT NULL DEFAULT 'prepared',
    performed_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_findesk_protected_group (group_id),
    KEY idx_findesk_protected_entity (entity_type, entity_id),
    KEY idx_findesk_protected_status (status),
    CONSTRAINT fk_findesk_protected_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_findesk_protected_user FOREIGN KEY (performed_by_user_id) REFERENCES users (id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
